version: '3'

services:

  servidor:
    build:
      context: ./images-apache
      dockerfile: Dockerfile
#    networks:
#      - code
#   image: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
       - ./images-apache/app:/usr/local/apache2/htdocs/
#    depends_on: 
#      - php
#    links:
#       - php
#  php:
#    build:
#      context: ./image-php
#      dockerfile: Dockerfile
#    networks:
#      - code
#    image: php
#    ports:
#      - "9000:9000"
#    expose:
#      - "9000"
#    volumes:
#      - ./images-apache/app:/usr/share/nginx/html
# networks:
#  code:
#    driver: bridge
