version: "3.9"

services:

  web:
    build:
      context: ./php-apache
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    volumes:
      - ./php-apache/src:/var/www/html/

    links:
      - mysqldb

  mysqldb:
    image: mysql

    ports:
      - "3308:3306"
      
    environment:
      - MYSQL_ROOT_PASSWORD=admin123.
      - MYSQL_DATABASE=testComposer